# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jzip}
  s.version = "1.0.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Engel"]
  s.date = %q{2010-09-03}
  s.description = %q{Jzip was created due to the need of simply merging and minifying Javascript files to reduce HTTP requests and file size of application assets. Using sprites for images and SASS for stylesheets only left javascripts not be optimized.
                           AssetPackager almost suited the solution, but it hasn't got enough flexibility in configuration. So with AssetPackager (for minification) and SASS (for merging with templates) as inspiration, I came up with Jzip.}
  s.email = %q{paul.engel@holder.nl}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "init.rb",
     "install.rb",
     "jzip.gemspec",
     "lib/jzip.rb",
     "lib/jzip/actionpack.rb",
     "lib/jzip/actionpack/action_controller/base.rb",
     "lib/jzip/assets.rb",
     "lib/jzip/core.rb",
     "lib/jzip/core/string.rb",
     "lib/jzip/core/string/analyzation.rb",
     "lib/jzip/engine.rb",
     "lib/jzip/engine/requirement.rb",
     "lib/jzip/engine/support/jsmin.rb",
     "lib/jzip/engine/support/minifier.rb",
     "lib/jzip/engine/support/notifier.rb",
     "lib/jzip/engine/template.rb",
     "lib/jzip/plugin.rb",
     "rails/init.rb",
     "tasks/jzip.rake",
     "test/actionpack/action_controller/base_test.rb",
     "test/core/string/analyzation_test.rb",
     "test/engine_test.rb",
     "test/javascripts/after/compressed/public/javascripts/backend.js",
     "test/javascripts/after/compressed/public/javascripts/defaults.js",
     "test/javascripts/after/compressed/public/javascripts/frontend.js",
     "test/javascripts/after/compressed/tmp/jzip/_minified_/assets/jzip/code_heroes/backend.js",
     "test/javascripts/after/compressed/tmp/jzip/_minified_/assets/jzip/code_heroes/frontend.js",
     "test/javascripts/after/compressed/tmp/jzip/_minified_/assets/jzip/shared/code_heroes.js",
     "test/javascripts/after/compressed/tmp/jzip/_minified_/assets/jzip/shared/code_heroes/ajaxify.js",
     "test/javascripts/after/compressed/tmp/jzip/_minified_/assets/jzip/shared/jquery/ajax_setup.js",
     "test/javascripts/after/compressed/tmp/jzip/_minified_/assets/jzip/shared/jquery/class.js",
     "test/javascripts/after/compressed/tmp/jzip/_minified_/assets/jzip/shared/jquery/components/core.js",
     "test/javascripts/after/compressed/tmp/jzip/_minified_/assets/jzip/shared/jquery/extensions/core.js",
     "test/javascripts/after/compressed/tmp/jzip/_minified_/assets/jzip/shared/jquery/extensions/deparam.js",
     "test/javascripts/after/compressed/tmp/jzip/_minified_/assets/jzip/shared/jquery/seat_holder.js",
     "test/javascripts/after/compressed/tmp/jzip/_minified_/assets/jzip/shared/native/extensions/array.js",
     "test/javascripts/after/compressed/tmp/jzip/_minified_/assets/jzip/shared/native/extensions/string.js",
     "test/javascripts/after/compressed/tmp/jzip/_minified_/assets/jzip/shared/native/log.js",
     "test/javascripts/after/compressed/tmp/jzip/_minified_/public/javascripts/application.js",
     "test/javascripts/after/compressed/tmp/jzip/_minified_/public/javascripts/controls.js",
     "test/javascripts/after/compressed/tmp/jzip/_minified_/public/javascripts/dragdrop.js",
     "test/javascripts/after/compressed/tmp/jzip/_minified_/public/javascripts/effects.js",
     "test/javascripts/after/compressed/tmp/jzip/_minified_/public/javascripts/prototype.js",
     "test/javascripts/after/compressed/tmp/jzip/_minified_/tmp/jzip/public/javascripts/shared/_shared.js",
     "test/javascripts/after/compressed/tmp/jzip/_minified_/tmp/jzip/public/javascripts/shared/jquery/_core.js",
     "test/javascripts/after/compressed/tmp/jzip/public/javascripts/shared/_shared.js",
     "test/javascripts/after/compressed/tmp/jzip/public/javascripts/shared/jquery/_core.js",
     "test/javascripts/after/uncompressed/public/javascripts/backend.js",
     "test/javascripts/after/uncompressed/public/javascripts/defaults.js",
     "test/javascripts/after/uncompressed/public/javascripts/frontend.js",
     "test/javascripts/after/uncompressed/tmp/jzip/public/javascripts/shared/_shared.js",
     "test/javascripts/after/uncompressed/tmp/jzip/public/javascripts/shared/jquery/_core.js",
     "test/javascripts/assets/jzip/backend.jz",
     "test/javascripts/assets/jzip/code_heroes/backend.js",
     "test/javascripts/assets/jzip/code_heroes/frontend.js",
     "test/javascripts/assets/jzip/defaults.jz",
     "test/javascripts/assets/jzip/frontend.jz",
     "test/javascripts/assets/jzip/shared/_shared.jz",
     "test/javascripts/assets/jzip/shared/code_heroes.js",
     "test/javascripts/assets/jzip/shared/code_heroes/ajaxify.js",
     "test/javascripts/assets/jzip/shared/jquery/_all.jz",
     "test/javascripts/assets/jzip/shared/jquery/_core.fxc-clip.jz",
     "test/javascripts/assets/jzip/shared/jquery/_core.jz",
     "test/javascripts/assets/jzip/shared/jquery/_core.uic-resizable.jz",
     "test/javascripts/assets/jzip/shared/jquery/_fxc-clip.jz",
     "test/javascripts/assets/jzip/shared/jquery/_fxc-clip.uic-resizable.jz",
     "test/javascripts/assets/jzip/shared/jquery/_uic-resizable.jz",
     "test/javascripts/assets/jzip/shared/jquery/ajax_setup.js",
     "test/javascripts/assets/jzip/shared/jquery/class.js",
     "test/javascripts/assets/jzip/shared/jquery/components/core.js",
     "test/javascripts/assets/jzip/shared/jquery/components/fxc-clip.js",
     "test/javascripts/assets/jzip/shared/jquery/components/uic-resizable.js",
     "test/javascripts/assets/jzip/shared/jquery/extensions/core.js",
     "test/javascripts/assets/jzip/shared/jquery/extensions/deparam.js",
     "test/javascripts/assets/jzip/shared/jquery/seat_holder.js",
     "test/javascripts/assets/jzip/shared/native/extensions/array.js",
     "test/javascripts/assets/jzip/shared/native/extensions/string.js",
     "test/javascripts/assets/jzip/shared/native/log.js",
     "test/javascripts/before/application.js",
     "test/javascripts/before/controls.js",
     "test/javascripts/before/dragdrop.js",
     "test/javascripts/before/effects.js",
     "test/javascripts/before/prototype.js",
     "test/rails_root/compressed/assets/jzip/foo.js",
     "test/rails_root/compressed/public/javascripts/foo.js",
     "test/rails_root/uncompressed/assets/jzip/foo.js",
     "test/rails_root/uncompressed/public/javascripts/foo.js",
     "test/setup.rb",
     "test/test_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/archan937/jzip}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Javascript merging and compression for Rails Apps}
  s.test_files = [
    "test/actionpack/action_controller/base_test.rb",
     "test/core/string/analyzation_test.rb",
     "test/engine_test.rb",
     "test/setup.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

